imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

redis:
    host: 10.10.10.21
    database: 0

gearman:
    servers:
        server1:
            host: 10.10.10.31
            port: 4730

memcache:
    servers:
        server1:
            host: 10.10.10.21 # 8192
            port: 11211
            weight: 40
        server2:
            host: 10.10.10.22 #12228
            port: 11211
            weight: 60