imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

redis:
    host: 10.10.10.21
    database: 0

gearman:
    servers:
        server1:
            host: 10.10.10.21
            #port: 123
        server2:
            host: 10.10.10.31
            #port: 123
        server2:
            host: 10.10.10.41
            #port: 123
        server2:
            host: 10.10.10.42
            #port: 123

memcache:
    servers:
        server1:
            host: 10.10.10.21
            port: 11211
            weight: 25
        server2:
            host: 10.10.10.31
            port: 11211
            weight: 25
        server3:
            host: 10.10.10.41
            port: 11211
            weight: 25
        server3:
            host: 10.10.10.42
            port: 11211
            weight: 25