imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

redis:
    nodes:
        node1:
            host: 10.10.10.21
            port: 6379
            timeout: 2.5

            options:
                persistent: true
                database: 0
                prefix: null

#        enable after migration

#        node2:
#            host: 10.10.10.22
#            port: 6379
#            timeout: 2.5
#
#            options:
#                persistent: true
#                database: 0
#                prefix: null

gearman:
    nodes:
        node1:
            host: 10.10.10.21
            port: 4730

#        enable after migration

#        node2:
#            host: 10.10.10.22 # memory2
#            port: 4730

memcache:
    nodes:
        node1:
            host: 10.10.10.21
            port: 11211
            weight: 40
        node2:
            host: 10.10.10.22
            port: 11211
            weight: 60