imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

redis:
    host: 10.10.10.21
    database: 0

gearman:
    servers:
        server1:
            host: 10.10.10.31
            port: 4730

memcache:
    servers:
        server1:
            host: 10.10.10.21
            port: 11211
            weight: 50
        server2:
            host: 10.10.10.31
            port: 11211
            weight: 8
        server3:
            host: 10.10.10.41
            port: 11211
            weight: 21
        server4:
            host: 10.10.10.42
            port: 11211
            weight: 21