imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'], assets_version: 'rev=2' } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       14400
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        closure:
            jar: %kernel.root_dir%/Resources/compilers/google-closure-compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/compilers/yui-compressor.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/compilers/yui-compressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        metadata_cache_driver: apc
        query_cache_driver: xcache
        result_cache_driver:
            type: memcache
            host: localhost
            port: 11211
            instance_class: Memcache

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

mamba:
    app_id: 355
    secret_key: 'jn6OUU2pS5nz7O37Srj9'
    private_key: 'Ot018UW4jOYQSWKpQ2l9'

redis:
    host: localhost
    database: 0

gearman:
    servers:
        server1:
            host: localhost
            #port: 123

memcache:
    servers:
        server1:
            host: localhost
            port: 11211
            weight: 25
#        server2:
#            host: localhost
#            port: 11211
#            weight: 75