security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                nastya:  { password: dOFupQMHuKWPphKGe4svuZVGNDbfnXyljDXXygdyKt2DPRRPFM, roles: [ 'ROLE_USER' ] }
                ilya:    { password: zDydGKrBzh1aXtpbcpzTpPBbldTZGvRpFVFMkXMYgrSyW7VbbL, roles: [ 'ROLE_ADMIN' ] }
                igor:    { password: XsKS2QALeHZFvfLstqdZRrZUsNTV6sNVdINxTOwuMWxaahqjRK, roles: [ 'ROLE_ADMIN' ] }
#                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/admin/
            anonymous: ~
            http_basic:
                realm: "Secured area"

    access_control:
        - { path: ^/admin/user*, roles: ROLE_USER }
        - { path: ^/admin/battery*, roles: ROLE_USER }
        - { path: ^/admin/energy*, roles: ROLE_USER }
        - { path: ^/admin/stats*, roles: ROLE_USER }
        - { path: ^/admin/\$*, roles: ROLE_ADMIN }
        - { path: ^/admin/decisions*, roles: ROLE_ADMIN }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
