parameters:
    mamba.class: Mamba\PlatformBundle\API\Mamba

services:
    mamba:
        class: %mamba.class%
        arguments: [%mamba.app_id%, %mamba.secret_key%, %mamba.private_key%, @session, @memcache, @redis]