Mamba\EncountersBundle\Entity\Billing:
  type: entity
  table: Billing
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    appId:
      type: integer
      unsigned: false
      nullable: true
      column: app_id
    userId:
      type: integer
      unsigned: false
      nullable: true
      column: user_id
    operationId:
      type: integer
      unsigned: false
      nullable: true
      column: operation_id
    amount:
      type: float
      nullable: true
    amountDeveloper:
      type: float
      nullable: true
      column: amount_developer
    validationId:
      type: integer
      unsigned: false
      nullable: true
      column: validation_id
    time:
      type: integer
      unsigned: false
      nullable: true
    sig:
      type: string
      length: 64
      fixed: false
      nullable: true
    billed:
      type: boolean
      nullable: true
  lifecycleCallbacks: {  }
