parameters:
#    gearman.example.class: Mamba\GearmanBundle\Example

services:
#    gearman.example:
#        class: %gearman.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
