parameters:
#    application_encounters.example.class: Application\EncountersBundle\Example

services:
#    application_encounters.example:
#        class: %application_encounters.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
