# Страницы

# Точка входа в приложение
welcome:
    pattern: /
    defaults: { _controller: EncountersBundle:Welcome:index }
    requirements:
        _method:  GET

# Страница настроек приложения
preferences:
    pattern: /preferences
    defaults: { _controller: EncountersBundle:Preferences:index }

# Страница игры
game:
    pattern: /game
    defaults: { _controller: EncountersBundle:Game:index }

# Страница взаимных симпатий
mutual:
    pattern: /mutual
    defaults: { _controller: EncountersBundle:Mutual:index }

# Страница моего хитлиста
visitors:
    pattern: /visitors
    defaults: { _controller: EncountersBundle:Visitors:index }

# Страница мной просмотренных
mychoice:
    pattern: /mychoice
    defaults: { _controller: EncountersBundle:MyChoice:index }

# Страница профиля
profile:
    pattern: /profile
    defaults: { _controller: EncountersBundle:Profile:index }

# AJAX методы

# Прием голосований
vote.set:
    pattern: /ajax/vote.set
    defaults: { _controller: EncountersBundle:Vote:ajaxVoteSet }
    requirements:
        #_method: POST раскоментить для продакшена

# Прием голосований
queue.get:
    pattern: /ajax/queue.get
    defaults: { _controller: EncountersBundle:Queue:ajaxQueueGet }
    requirements:
        #_method: POST раскоментить для продакшена