EncountersBundle_EntryPoint:
    pattern:  /
    defaults: { _controller: EncountersBundle:Default:index }
    requirements:
        _method:  GET

EncountersBundle_OptionsPoint:
    pattern:  /options
    defaults: { _controller: EncountersBundle:Options:index }
    requirements:
        _method:  GET

EncountersBundle_JsonAPI:
    pattern:  /json-api/{method}
    defaults: { _controller: EncountersBundle:JsonApi:index }
    requirements:
        _method:  GET